version: 2

sources:
  - name: jaffle_shop
    database: raw  
    schema: jaffle_shop  
    tables:
      - name: orders
        freshness:
          warn_after:
            count: 12
            period: day
        loaded_at_field: _etl_loaded_at
      - name: customers

  - name: stripe
    database: raw
    schema: stripe
    tables:
      - name: payment